repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        types_or: [python, pyi]
      - id: ruff-format
        args: [--check]
        types_or: [python, pyi]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        additional_dependencies:
          - mypy
          - types-requests
          - types-setuptools
        args: [
          ".",
          "--ignore-missing-imports",
          "--explicit-package-bases",
        ]
        types: [python]
        pass_filenames: false
        require_serial: true
  
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: python
        additional_dependencies:
          - pytest
          - "loguru~=0.7.0"
          - "cirpy~=1.0.0"
          - "chemspipy~=2.0.0"
          - "requests"
          - "flashtext"
          - "py2opsin @ git+https://github.com/denovochem/py2opsin.git"
          - "PubChemPy @ git+https://github.com/denovochem/PubChemPy.git"
          - .
        pass_filenames: false
        types: [python]
        stages: [pre-push]